/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;
import modelo.CalculosEsfera;

/**
 *
 * @author Edgar
 */
public class PanelEsfera extends javax.swing.JPanel {

    /**
     * Creates new form panelEsfera
     */
    public PanelEsfera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valoresCuadradosJTF = new javax.swing.JTextField();
        valoresLinealesJTF = new javax.swing.JTextField();
        valorConstanteJTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        despliegueJL = new javax.swing.JList();
        bCalcular = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Inserte los coeficientes de x^2,y^2,z^2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Inserte los coeficientes de x, y, z");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Inserte el valor de c");

        valoresCuadradosJTF.setColumns(20);
        valoresCuadradosJTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valoresCuadradosJTF.setText("16");
        valoresCuadradosJTF.setToolTipText("Introduzca solo un numero de los coeficientes");

        valoresLinealesJTF.setColumns(20);
        valoresLinealesJTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valoresLinealesJTF.setText("-16/8/-32");
        valoresLinealesJTF.setToolTipText("Separe los valores por diagonales (/)");

        valorConstanteJTF.setColumns(20);
        valorConstanteJTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorConstanteJTF.setText("16");
        valorConstanteJTF.setToolTipText("Introduzca un único valor entero ");

        despliegueJL.setToolTipText("Aquí se presentan los resultados");
        jScrollPane1.setViewportView(despliegueJL);

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorConstanteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valoresLinealesJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valoresCuadradosJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCalcular)
                .addGap(18, 18, 18)
                .addComponent(bLimpiar)
                .addGap(18, 18, 18)
                .addComponent(bSalir)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valoresCuadradosJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valoresLinealesJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorConstanteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCalcular)
                    .addComponent(bSalir)
                    .addComponent(bLimpiar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        this.valorConstanteJTF.setText("");
        this.valoresCuadradosJTF.setText("");
        this.valoresLinealesJTF.setText("");
        DefaultListModel modelo = new DefaultListModel();
        this.despliegueJL.setModel(modelo);
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        try{
            modelo.addElement("");
            this.despliegueJL.setModel(modelo);
            CalculosEsfera c = new CalculosEsfera(this);
        }catch(Exception e){
            modelo.addElement("E R R O R ! ! ! !");
            modelo.addElement("Revise los datos introducidos. Vuelva a intentarlo.");
            this.despliegueJL.setModel(modelo);
        }
        
        
        
    }//GEN-LAST:event_bCalcularActionPerformed

    public void setDespliegueJL(DefaultListModel modelo) {
        this.despliegueJL.setModel(modelo);
    }

    public JTextField getValorConstanteJTF() {
        return valorConstanteJTF;
    }

    public JTextField getValoresCuadradosJTF() {
        return valoresCuadradosJTF;
    }

    public JTextField getValoresLinealesJTF() {
        return valoresLinealesJTF;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bSalir;
    private javax.swing.JList despliegueJL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorConstanteJTF;
    private javax.swing.JTextField valoresCuadradosJTF;
    private javax.swing.JTextField valoresLinealesJTF;
    // End of variables declaration//GEN-END:variables
}
